

```{r, , label="{{x}}a", include=FALSE}
#print({{x}})
#lh<-grabber[[{{x}}]]
#print(lh)
```






```{r, , label="{{x}}b", include = FALSE, echo = FALSE, out.width = "90%"}



# names <- c("L units:",
#             "Walpha units:", 
#             "L infinity:", 
#             "K:", 
#             "L50:", 
#             "L95:", 
#             "M:", 
#             "MK:", 
#             "LW A:", 
#             "LW B:", 
#             "T max:", 
#             "Steep:")
# 
# values <- c("{{lh@L_units}}",
#             "{{lh@Walpha_units}}", 
#             "{{lh@Linf}}", 
#             "{{lh@K}}", 
#             "{{lh@L50}}", 
#             "{{lh@L95}}", 
#             "{{lh@M}}", 
#             "{{lh@MK}}", 
#             "{{lh@LW_A}}", 
#             "{{lh@LW_B}}", 
#             "{{lh@Tmax}}", 
#             "{{lh@Steep}}")
# 
# param_df <- data.frame(names, values)

# knitr::kable(param_df, 
#              col.names = c('Parameters', 'Value'), 
#              align = "lc") %>% 
#   add_header_above(c("{{lh@speciesName}} Life History Parameters" = 2)) %>% 
#   kable_styling(bootstrap_options = c("hover",
#                                       "condensed", 
#                                       "responsive"), 
#                 full_width = T, 
#                 fixed_thead = T)


 # knitr::kable(
 #              LH_to_dataframe(LifeHistoryObj={{lh}}, digits=3) %>%
 #                filter(across(any_of("key"), ~.x != "Beverton-Holt steepness")) %>%
 #                filter(across(any_of("key"), ~.x != "Title")) %>%
 #                filter(across(any_of("key"), ~.x != "Short description")) %>%
 #                filter(across(any_of("key"), ~.x != "Long description")) %>%
 #                filter(across(any_of("key"), ~.x != "Author")) %>%
 #                filter(across(any_of("key"), ~.x != "Author affiliation")),
 #              col.names = c('Parameter', 'Value'),
 #              align = "lc"
 #            ) %>%
 #              kable_styling(
 #                bootstrap_options = "hover"
 #              )
```




